update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -94,16 +94,14 @@ jobs:
       - checkout
       - oss/npm_clean_install_with_caching
       - run:
-          name: Generate types locally
+          name: Generate types locally and compare type files
           command: |
             if [ -z "$CHECKS_API_KEY" ]; then
               echo "NO CHECKS_API_KEY! CANNOT RUN! This is normal on PRs from Forks."
               exit 0 # i.e. pass tests.
             fi
             npx apollo client:codegen --key=$CHECKS_API_KEY --outputFlat --target=typescript currentTypes.ts
-      - run:
-          name: Compare type files
-          command: cmp --silent currentTypes.ts ./packages/apollo-language-server/src/graphqlTypes.ts || (echo "Type check failed. Run 'npm run client:codegen'" && exit 1)
+            cmp --silent currentTypes.ts ./packages/apollo-language-server/src/graphqlTypes.ts || (echo "Type check failed. Run 'npm run client:codegen'" && exit 1)
 
 common_non_publish_filters: &common_non_publish_filters
   filters:
@@ -160,4 +158,3 @@ workflows:
           <<: *common_publish_filters
           requires:
             - Confirmation
-
